# Generated by Django 4.2.4 on 2023-08-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_options_remove_women_photo_womenphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
        migrations.AlterModelOptions(
            name='womenphoto',
            options={'verbose_name': 'Фотография известной женщины', 'verbose_name_plural': 'Фотографии известных женщин'},
        ),
        migrations.AddField(
            model_name='women',
            name='first_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='women.womenphoto', verbose_name='Фотография'),
        ),
    ]
